### PR TITLE
Update expo

### PR DESCRIPTION
**Pull request by mixcas**
Also remove everything related to `native-base`

DO:
```
rm -rf node_modules
yarn
yarn start
``` 
Then when expo is running press `R` to clean cache and restart packager

Also update your `react-native-debugger` by running:
 `brew cask upgrade react-native-debugger`

### CODE REVIEW

**Comment by mixcas** [comment]
@varffs it may take ur computer a whole day to rebuild. go grab a coffee, mate. ❤️

**Review by varffs — APPROVED** [review]
This works fine for me so I'm sure can be merged. (even builds faster finally) But probably worth someone checking on their local too before a merge.

(Was it required to remove native-base for this or just a mashup?)

**Comment by mixcas** [comment]
@varffs i had to remove `native-base` because weirdly, it was the only thing breaking after the updates.

@mikeyrayvon could u try this too?

**Comment by mikeyrayvon** [comment]
i'm checking it out now

**Comment by mikeyrayvon** [comment]
ok runs clean. not sure what to do with this conflict though... @mixcas ?

**Comment by mikeyrayvon** [comment]
nevermind its just a matter of running `yarn` in the merge:

```
17:03:01 app-andamiaje-co 🌸 yarn
yarn install v1.5.1
info Merge conflict detected in yarn.lock and successfully merged.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
```

**Pull request merged**
